version: '3.1'

services:

  #Web server management
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '90:80'
    volumes:
      - ./html:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  web:
    external: true